version: 1
packages:
  - version: commit:417d65df68dad4d2e6bbb1896c8b18400ca3e035
    name: dimension_package
    url: https://github.com/sydneypark/telus_atscale-container-dimension-package
    branch: main
