version: 1
packages:
  - version: commit:632498acec4ec097825c9a247e8471ec54257bce
    name: dimension_package
    url: https://github.com/sydneypark/telus_atscale-container-dimension-package
    branch: main
