unique_name: _0X0355_ECC_CSFBCONFIGFAILURE_EMTC_CALL_FAIL
object_type: metric
label: _0x0355_Ecc_CSFBConfigFailure_count
calculation_method: sum
dataset: lte-emtc-call-fail
column: _0x0355_Ecc_CSFBConfigFailure_count
