unique_name: _0X0909_MAC_INVALIDRBCONFIG_EMTC_CALL_FAIL
object_type: metric
label: _0x0909_Mac_InvalidRbConfig_count
calculation_method: sum
dataset: lte-emtc-call-fail
column: _0x0909_Mac_InvalidRbConfig_count
