unique_name: _0X0301_ECCTMOUT_RRCCONNECTIONRECONFIGCOMPLETE
object_type: metric
label: _0x0301_EccTmout_RrcConnectionReconfigComplete_count
calculation_method: sum
dataset: lte-call-fail
column: _0x0301_EccTmout_RrcConnectionReconfigComplete_count
