unique_name: _0X0909_MAC_INVALIDRBCONFIG_NB_IOT_CALL_FAIL_CE_LEVEL
object_type: metric
label: _0x0909_Mac_InvalidRbConfig_count
calculation_method: sum
dataset: lte-nb-iot-call-fail-per-ce-level
column: _0x0909_Mac_InvalidRbConfig_count
