unique_name: _0X0301_ECCTMOUT_RRCCONNECTIONRECONFIGCOMPLETE_NB_IOT_CALL_F
object_type: metric
label: _0x0301_EccTmout_RrcConnectionReconfigComplete_count
calculation_method: sum
dataset: lte-nb-iot-call-fail
column: _0x0301_EccTmout_RrcConnectionReconfigComplete_count
