unique_name: _0X0301_ECCTMOUT_RRCCONNECTIONRECONFIGCOMPLETE_EMTC_CALL_FAIL
object_type: metric
label: _0x0301_EccTmout_RrcConnectionReconfigComplete_count
calculation_method: sum
dataset: lte-emtc-call-fail
column: _0x0301_EccTmout_RrcConnectionReconfigComplete_count
