unique_name: CALLDROPQCI_ECCBTMOUTRRCCONNECTIONRECONFIG
object_type: metric
label: CallDropQci_EccbTmoutRrcConnectionReconfig_count
calculation_method: sum
dataset: lte-call-drop-per-qci
column: CallDropQci_EccbTmoutRrcConnectionReconfig_count
