unique_name: CALLDROP_ECCBTMOUTRRCCONNECTIONRECONFIG
object_type: metric
label: CallDrop_EccbTmoutRrcConnectionReconfig_count
calculation_method: sum
dataset: lte-call-drop
column: CallDrop_EccbTmoutRrcConnectionReconfig_count
