unique_name: CELEVEL_NBIOT_CALLDROP_NCCBTMOUTRRCCONNECTIONRECONFIG
object_type: metric
label: CELevel_NBIoT_CallDrop_NccbTmoutRrcConnectionReconfig_count
calculation_method: sum
dataset: lte-nb-iot-call-drop-per-ce-level
column: CELevel_NBIoT_CallDrop_NccbTmoutRrcConnectionReconfig_count
