unique_name: CELEVEL_EMTC_CALLDROPQCI_ECCBTMOUTRRCCONNECTIONRECONFIG
object_type: metric
label: CELevel_eMTC_CallDropQci_EccbTmoutRrcConnectionReconfig_count
calculation_method: sum
dataset: lte-emtc-e-rab-setup-add-and-call-drop-qci-per-ce-level
column: CELevel_eMTC_CallDropQci_EccbTmoutRrcConnectionReconfig_count
