unique_name: EMTC_CONNRECONFIGATT
object_type: metric
label: eMTC_ConnReconfigAtt_count
calculation_method: sum
dataset: lte-emtc-rrc-connection-reconfiguration
column: eMTC_ConnReconfigAtt_count
