unique_name: EMTC_CALLDROPQCI_ECCBTMOUTRRCCONNECTIONRECONFIG
object_type: metric
label: eMTC_CallDropQci_EccbTmoutRrcConnectionReconfig_count
calculation_method: sum
dataset: lte-emtc-call-drop-per-qci
column: eMTC_CallDropQci_EccbTmoutRrcConnectionReconfig_count
