unique_name: EMTC_CALLDROP_ECCBTMOUTRRCCONNECTIONRECONFIG
object_type: metric
label: eMTC_CallDrop_EccbTmoutRrcConnectionReconfig_count
calculation_method: sum
dataset: lte-emtc-call-drop
column: eMTC_CallDrop_EccbTmoutRrcConnectionReconfig_count
