unique_name: EMTC_RELACTIVE_ECCBTMOUTRRCCONNECTIONRECONFIG
object_type: metric
label: eMTC_RelActive_EccbTmoutRrcConnectionReconfig_count
calculation_method: sum
dataset: lte-emtc-e-rab-release
column: eMTC_RelActive_EccbTmoutRrcConnectionReconfig_count
