unique_name: ENDC_RELREQUEST_DL_RLF_SCG_RECONFIGFAILURE
object_type: metric
label: EnDc_RelRequest_DL_RLF_scg_reconfigFailure_count
calculation_method: sum
dataset: lte-en-dc-release-information
column: EnDc_RelRequest_DL_RLF_scg_reconfigFailure_count
