unique_name: ENDC_RELREQUEST_DL_RLF_SYNCHRECONFIGFAILURE_SCG
object_type: metric
label: EnDc_RelRequest_DL_RLF_synchReconfigFailure_SCG_count
calculation_method: sum
dataset: lte-en-dc-release-information
column: EnDc_RelRequest_DL_RLF_synchReconfigFailure_SCG_count
