unique_name: ENDC_ADDRRCRECONFIGSUCC_NRNCR
object_type: metric
label: EnDc_AddRrcReconfigSucc_NrNcr_count
calculation_method: sum
dataset: lte-en-dc-addition-information-per-nr-ncr
column: EnDc_AddRrcReconfigSucc_NrNcr_count
