unique_name: ENDC_ERABESTABFAIL_RRCRECONFIGTO
object_type: metric
label: EnDc_ErabEstabFail_RrcReconfigTO_count
calculation_method: sum
dataset: lte-en-dc-e-rab-establish-information
column: EnDc_ErabEstabFail_RrcReconfigTO_count
