unique_name: EPECURRENTAVGCNT_LTE_ENERGY_POWER_ENVIRONMENTAL_STATISTICS_M
object_type: metric
label: EpeCurrentAvgCnt_count
calculation_method: sum
dataset: lte-energy-power-and-environmental-statistics-of-mplane
column: EpeCurrentAvgCnt_count
