unique_name: EPECURRENTMINCNT_LTE_ENERGY_POWER_ENVIRONMENTAL_STATISTICS_M
object_type: metric
label: EpeCurrentMinCnt_count
calculation_method: sum
dataset: lte-energy-power-and-environmental-statistics-of-mplane
column: EpeCurrentMinCnt_count
