unique_name: EPEPOWERMAXCNT_LTE_ENERGY_POWER_ENVIRONMENTAL_STATISTICS_MPL
object_type: metric
label: EpePowerMaxCnt_count
calculation_method: sum
dataset: lte-energy-power-and-environmental-statistics-of-mplane
column: EpePowerMaxCnt_count
