unique_name: EPETEMPAVG_C_LTE_ENERGY_POWER_ENVIRONMENTAL_STATISTICS_MPLANE
object_type: metric
label: EpeTempAvg_C
calculation_method: sum
dataset: lte-energy-power-and-environmental-statistics-of-mplane
column: EpeTempAvg_C
