unique_name: EPETEMPMAXCNT_LTE_ENERGY_POWER_ENVIRONMENTAL_STATISTICS_MPLANE
object_type: metric
label: EpeTempMaxCnt_count
calculation_method: sum
dataset: lte-energy-power-and-environmental-statistics-of-mplane
column: EpeTempMaxCnt_count
