unique_name: EPEVOLTAGEMINCNT_LTE_ENERGY_POWER_ENVIRONMENTAL_STATISTICS_M
object_type: metric
label: EpeVoltageMinCnt_count
calculation_method: sum
dataset: lte-energy-power-and-environmental-statistics-of-mplane
column: EpeVoltageMinCnt_count
