unique_name: EPEVOLTAGEAVG_V_LTE_ENERGY_POWER_ENVIRONMENTAL_STATISTICS_MP
object_type: metric
label: EpeVoltageAvg_V
calculation_method: sum
dataset: lte-energy-power-and-environmental-statistics-of-mplane
column: EpeVoltageAvg_V
