unique_name: EPEVOLTAGEAVGCNT_LTE_ENERGY_POWER_ENVIRONMENTAL_STATISTICS_M
object_type: metric
label: EpeVoltageAvgCnt_count
calculation_method: sum
dataset: lte-energy-power-and-environmental-statistics-of-mplane
column: EpeVoltageAvgCnt_count
