unique_name: ERABINFO_CALLDROP_TMOUTRRCCONNECTIONRECONFIG
object_type: metric
label: ErabInfo_CallDrop_TmoutRrcConnectionReconfig_count
calculation_method: sum
dataset: lte-e-rab-setup-modification-release-information-per-plmn-and-q
column: ErabInfo_CallDrop_TmoutRrcConnectionReconfig_count
