unique_name: INTRAMENBTOMENBNOSGNBCHG_MODFAIL_RRCRECONFIGTO
object_type: metric
label: IntraMenbToMenbNoSgnbChg_ModFail_RrcReconfigTO_count
calculation_method: sum
dataset: lte-sgnb-modification-due-to-mcg-mobility
column: IntraMenbToMenbNoSgnbChg_ModFail_RrcReconfigTO_count
