unique_name: LOGGEDMDTCONFIGURATIONCNT
object_type: metric
label: LoggedMDTConfigurationCnt_count
calculation_method: sum
dataset: lte-mdt-configuration-and-delivery
column: LoggedMDTConfigurationCnt_count
