unique_name: NBIOT_S1APMMECONFIGURATIONUPDATEFAILURE
object_type: metric
label: NBIoT_S1apMMEConfigurationUpdateFailure_count
calculation_method: sum
dataset: lte-nb-iot-s1ap-message
column: NBIoT_S1apMMEConfigurationUpdateFailure_count
