unique_name: NBIOT_S1APENBCONFIGURATIONUPDATEACKNOWLEDGE
object_type: metric
label: NBIoT_S1apENBConfigurationUpdateAcknowledge_count
calculation_method: sum
dataset: lte-nb-iot-s1ap-message
column: NBIoT_S1apENBConfigurationUpdateAcknowledge_count
