unique_name: NBIOT_RELACTIVE_TMOUTRRCCONNECTIONRECONFIG
object_type: metric
label: NBIoT_RelActive_TmoutRrcConnectionReconfig_count
calculation_method: sum
dataset: lte-nb-iot-e-rab-release
column: NBIoT_RelActive_TmoutRrcConnectionReconfig_count
