unique_name: NBIOT_S1APENBCONFIGURATIONUPDATEFAILURE
object_type: metric
label: NBIoT_S1apENBConfigurationUpdateFailure_count
calculation_method: sum
dataset: lte-nb-iot-s1ap-message
column: NBIoT_S1apENBConfigurationUpdateFailure_count
