unique_name: NBIOT_CALLDROP_NCCBTMOUTRRCCONNECTIONRECONFIG
object_type: metric
label: NBIoT_CallDrop_NccbTmoutRrcConnectionReconfig_count
calculation_method: sum
dataset: lte-nb-iot-call-drop
column: NBIoT_CallDrop_NccbTmoutRrcConnectionReconfig_count
