unique_name: RRCRRCCONNECTIONRECONFIGURATION
object_type: metric
label: RrcRrcConnectionReconfiguration_count
calculation_method: sum
dataset: lte-rrc-message-per-cell
column: RrcRrcConnectionReconfiguration_count
