unique_name: SGNB_ADDFAIL_RRCRECONFIGTO_SCG_MOBILITY
object_type: metric
label: Sgnb_AddFail_RrcReconfigTO_count
calculation_method: sum
dataset: lte-sgnb-addition-due-to-scg-mobility
column: Sgnb_AddFail_RrcReconfigTO_count
