unique_name: SGNB_ADDFAIL_RRCRECONFIGTO
object_type: metric
label: Sgnb_AddFail_RrcReconfigTO_count
calculation_method: sum
dataset: lte-sgnb-addition-due-to-mcg-mobility
column: Sgnb_AddFail_RrcReconfigTO_count
