unique_name: ULMUMIMOPAIREDUEPERTTI_MASSIVE_MIMO_CONFIGURATION
object_type: metric
label: ULMuMimoPairedUEperTti_count
calculation_method: sum
dataset: lte-uplink-multi-user-mimo-in-massive-mimo-configuration
column: ULMuMimoPairedUEperTti_count
