unique_name: ULSCELLDECONFIGBYEVENTA6
object_type: metric
label: ULSCellDeconfigByEventA6_count
calculation_method: sum
dataset: lte-uplink-carrier-aggregation-count-for-configuration-deconfig
column: ULSCellDeconfigByEventA6_count
